language: java
install: true

jdk:
  - oraclejdk11

script:
  - ./gradlew build --scan -s
  - ./gradlew jacocoTestReport

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper

after_success:
  - bash <(curl -s https://codecov.io/bash)